// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-JIkjLNjB9myM4sxvd7L5fygu8oEM6KM',
    appId: '1:1048150718789:web:dcc7cac08206c64d60e62c',
    messagingSenderId: '1048150718789',
    projectId: 'readrover-eb615',
    authDomain: 'readrover-eb615.firebaseapp.com',
    storageBucket: 'readrover-eb615.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrIeV5oc25A5eN1dD7eKDQzCPtzcttJfk',
    appId: '1:1048150718789:android:bff1bbc3f570f91b60e62c',
    messagingSenderId: '1048150718789',
    projectId: 'readrover-eb615',
    storageBucket: 'readrover-eb615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfdtTSwNqFGMayMCthvK6X8c5xXLHTU4M',
    appId: '1:1048150718789:ios:c50c14ad629419e660e62c',
    messagingSenderId: '1048150718789',
    projectId: 'readrover-eb615',
    storageBucket: 'readrover-eb615.appspot.com',
    iosBundleId: 'com.example.flutterReadrover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfdtTSwNqFGMayMCthvK6X8c5xXLHTU4M',
    appId: '1:1048150718789:ios:9c6d3d5e1339b88760e62c',
    messagingSenderId: '1048150718789',
    projectId: 'readrover-eb615',
    storageBucket: 'readrover-eb615.appspot.com',
    iosBundleId: 'com.example.flutterReadrover.RunnerTests',
  );
}
